services:
  the-nest:
    image: grumnuts/the-nest:latest
    container_name: the-nest
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=CHANGE_ME_TO_RANDOM_32_CHAR_SECRET
      - CLIENT_URL=http://localhost:5000
      - TZ=UTC
      - PUID=1001 # Optional
      - PGID=1001 # Optional
    volumes:
      - ./the_nest.db:/app/data/the_nest.db
    restart: unless-stopped

